blog:
  build: frontend/.
  command: bash -c "npm start"
  container_name: blog_frontend
  ports:
    - '80:80'
    - '3000:3000'
  volumes:
    - ./frontend:/usr/src
    - /usr/src/node_modules
api:
  build: backend/.
  command: node api.js
  container_name: blog_api
  ports:
    - '1234:1234'
  volumes:
    - ./backend:/usr/src
    - /usr/src/node_modules
