blog:
  build: frontend/.
  container_name: blog_frontend
  command: bash -c "npm run compile && nginx -g 'daemon off;'"
  ports:
    - '80:80'
  tty: true

api:
  build: backend/.
  container_name: blog_api
  command: node api.js
  ports:
    - '1234:1234'
